name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Test PHP ${{ matrix.php_version }} - ${{ matrix.dependency-mode }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version:
          - '8.2'
          - '8.3'
          - '8.4'
        dependency-mode:
          - 'stable'
          - 'lowest'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, assert.exception=1
          coverage: pcov
          tools: composer:latest

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php_version }}-${{ matrix.dependency-mode }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php_version }}-${{ matrix.dependency-mode }}-
            ${{ runner.os }}-php-${{ matrix.php_version }}-

      - name: Install Dependencies (Stable)
        if: matrix.dependency-mode == 'stable'
        run: composer update --prefer-dist --no-interaction --prefer-stable

      - name: Install Dependencies (Lowest)
        if: matrix.dependency-mode == 'lowest'
        run: composer update --prefer-dist --no-interaction --prefer-lowest

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit tests --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: PHP ${{ matrix.php_version }} - ${{ matrix.dependency-mode }}
          fail_ci_if_error: false

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov
          tools: composer:latest

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-coverage-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-coverage-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Generate Coverage Report
        run: ./vendor/bin/phpunit tests --coverage-text --coverage-html=coverage-report

      - name: Upload Coverage HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
